### DISCUSSION TITLE
"SSL is required" with 2.2.5 and MariaDB LTS on Win11

### DISCUSSION THREAD

**Discussion by GitRon** [PyMySQL/mysqlclient#736] [Q&A]
Hi there!

I installed the lastest bugfix release and I get an error in combination with Django (5.1) on Windows 11 and Mariadb (LTS 10.6) as a docker-compose service.

> django.db.utils.OperationalError: (2026, 'TLS/SSL error: SSL is required, but the server does not support it')

It's definitely linked to the bugfix release, 2.2.4 works.

I run the MariaDB locally via docker-compose:

```yml
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: my-pw
      MYSQL_DATABASE: my-project
      MYSQL_USER: my-project
      MYSQL_PASSWORD: mypw
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
```

The Django backend runs in a venv on Win11.

Any ideas? I've been googling around for quite a while now but don't really find a solution.

Update: When I upgrade to MariaDB 11.4, it works... but 10.6 is a valid LTS until 2026. This should work, right?

Thx and best regards  
Ronny
